---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Ubuntu
    image: python:3.7.13-slim
    pre_build_image: true
# test_sequence:
#   - lint
#   - destroy
#   - dependency
#   - syntax
#   - create
#   - converge
#   - idempotence
#   - verify
#   - destroy
provisioner:
  name: ansible
  config_options:
    defaults:
      become: false
verifier:
  name: testinfra
lint: |
  set -e
  yamllint .
  ansible-lint .
