---
- name: Create Source Control Credentials
  awx.awx.credential:
    name: "git_read"
    description: "Source Control Credential for Ansible repositories"
    organization: "{{ v_awx_organizations[0].name }}"
    credential_type: "Source Control"
    inputs:
      username: "{{ v_awx_repo_username }}"
      password: "{{ v_awx_repo_password }}"
    state: present
    controller_host: "{{ v_awx_node_ip }}:{{ v_awx_node_port }}"
    controller_username: "admin"
    controller_password: "{{ v_awx_admin_password }}"
    validate_certs: false

- name: Create Machine Credentials
  awx.awx.credential:
    name: "{{ v_cred_machine }}"
    description: "Machine Credential for remote access"
    organization: "{{ v_awx_organizations[0].name }}"
    credential_type: "Machine"
    inputs:
      username: "{{ v_cred_machine_user }}"
      password: "{{ v_cred_machine_pass }}"
    state: present
    controller_host: "{{ v_awx_node_ip }}:{{ v_awx_node_port }}"
    controller_username: "admin"
    controller_password: "{{ v_awx_admin_password }}"
    validate_certs: false

- name: Create Vault Credentials
  awx.awx.credential:
    name: "{{ v_cred_vault }}"
    description: "Vault Credential for remote access"
    organization: "{{ v_awx_organizations[0].name }}"
    credential_type: "Vault"
    inputs:
      vault_password: "{{ v_cred_vault_value }}"
    state: present
    controller_host: "{{ v_awx_node_ip }}:{{ v_awx_node_port }}"
    controller_username: "admin"
    controller_password: "{{ v_awx_admin_password }}"
    validate_certs: false
