---
- name: Create Organizations
  awx.awx.organization:
     name: "{{ item.name }}"
     description: "{{ item.description }}"
     state: present
     galaxy_credentials:
        - Ansible Galaxy
     controller_host: "{{ v_awx_node_ip }}:{{ v_awx_node_port }}"
     controller_username: "admin"
     controller_password: "{{ v_awx_admin_password }}"
     validate_certs: false
  loop: "{{ v_awx_organizations }}"
