---
- name: Apply AWX settings
  awx.awx.settings:
    controller_host: "{{ v_awx_node_ip }}:{{ v_awx_node_port }}"
    controller_username: "admin"
    controller_password: "{{ v_awx_admin_password }}"
    validate_certs: false
    settings:
      PROJECT_UPDATE_VVV: false
      AWX_ROLES_ENABLED: true
      AWX_COLLECTIONS_ENABLED: true
      TOWER_URL_BASE: "{{ v_awx_node_ip }}"
