---
- name: Create inventory for project-{{ current_project.name }}
  awx.awx.inventory:
    name: '{{ v_inventory_name ~ "_" ~ current_project.name }}'
    description: '{{ v_inventory_name ~ "_" ~ current_project.name }}'
    organization: "{{ current_project.organization | default(v_awx_organizations[0].name) }}"
    controller_host: "{{ v_awx_node_ip }}:{{ v_awx_node_port }}"
    controller_username: "admin"
    controller_password: "{{ v_awx_admin_password }}"
    validate_certs: false
    state: '{{ current_project.state | default("present") }}'

- name: Assign role on inventory
  awx.awx.role:
    inventories: ['{{ v_inventory_name ~ "_" ~ current_project.name }}']
    role: "use"
    team: "{{ v_awx_organizations[0].name }}"
    controller_host: "{{ v_awx_node_ip }}:{{ v_awx_node_port }}"
    controller_username: "admin"
    controller_password: "{{ v_awx_admin_password }}"
    validate_certs: false
  when: current_project.state | default("present") == "present"

- name: Create source inventory for project-{{ current_project.name }}
  awx.awx.inventory_source:
    name: '{{ v_inventory_name ~ "_" ~ current_project.name }}-src'
    inventory: '{{ v_inventory_name ~ "_" ~ current_project.name }}'
    organization: "{{ current_project.organization | default(v_awx_organizations[0].name) }}"
    overwrite: true
    overwrite_vars: true
    update_on_launch: true
    source_path: '{{ "hosts_" ~ v_inventory_name }}'
    source: scm
    source_project: "project-{{ current_project.name }}"
    update_cache_timeout: 300
    controller_host: "{{ v_awx_node_ip }}:{{ v_awx_node_port }}"
    controller_username: "admin"
    controller_password: "{{ v_awx_admin_password }}"
    validate_certs: false
  when: current_project.state | default("present") == "present"
