---
- name: set variables for schedules
  set_fact:
    job_name: 'job_{{ current_template.inventory ~ "_" ~ current_project.name }}_{{ current_job.suffix }}'
    job_template_name: "{{ v_template_name }}"

- name: Create Schedule for job {{ job_name }}
  awx.awx.schedule:
    name: "{{ job_name }}"
    unified_job_template: "{{ job_template_name }}"
    enabled: "{{ current_job.enabled | default(false) }}"
    skip_tags: '{{ current_job.skip_tags | default("") }}'
    job_tags: '{{ current_job.job_tags | default("") }}'
    limit: '{{ current_job.limit | default("") }}'
    rrule: "{{ query('awx.awx.schedule_rruleset', current_job.start_date, rules=current_job.rrules) }}"
    controller_host: "{{ v_awx_node_ip }}:{{ v_awx_node_port }}"
    controller_username: "admin"
    controller_password: "{{ v_awx_admin_password }}"
    validate_certs: false
    state: '{{ current_job.state | default("present")  }}'
  when: current_template.template_base | default(true)

- name: Add job to current valid jobs
  set_fact:
    current_valid_jobs: "{{ current_valid_jobs }} + ['{{ job_name }}']"
  when: current_job.state | default("present") == "present"
