---
version: 3

images:
  base_image:
    name: quay.io/ansible/awx-ee:23.8.0

dependencies:
  system: dependencies/bindep.txt
  python: dependencies/requirements.txt
  galaxy: dependencies/requirements.yml

additional_build_steps:
  append_base:
    - RUN yum install -y yum-utils
    - RUN yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    - RUN yum -y install terraform
    - RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc
